### ISSUE TITLE
unable to load 

### ISSUE THREAD

**Issue by vishwarajsali** [invu/movieo-app#9]

**Comment by invu** [comment]
What's the exception message?

**Comment by Josh7234** [comment]
i have the same problem, i open it up, and if i click on anything else its comes up with a (not responding) message in the top. If I leave it, it takes around 5 minutes to come up with a few movies mybe 8-12

**Comment by invu** [comment]
Hopefully fixed all issues in update 3.3

**Comment by Josh7234** [comment]
i downloaded from the readme files on here and it still crashes, not sure if thats the new version yet?

**Comment by invu** [comment]
Download the installer at http://movieo.info/movieo-setup.zip
